---
abstract: 'Easy way to communicate with Barracuda API version 4.x and above'
author:
  - 'Mael Regnery <mql@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Barracuda-Api
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '1.25'
  XML::RPC: '0.8'
version: '0.02'
